[package]
name = "sample-tx"
version = "1.0.0"
authors = ["Valerio Mellini"]

[addresses]
tx = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
